# Generated by Django 3.1.7 on 2021-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
